// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6VvaQQ9Ky8cyryLoQ_SoSghwsTWEbLUo',
    appId: '1:117150854963:web:3228fa39ec5a58b61a9846',
    messagingSenderId: '117150854963',
    projectId: 'vcblry-v2',
    authDomain: 'vcblry-v2.firebaseapp.com',
    storageBucket: 'vcblry-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAUrZArzWYvKf4I9URCwo_OYDIEZsf0g',
    appId: '1:117150854963:android:8edba5df53f0b1101a9846',
    messagingSenderId: '117150854963',
    projectId: 'vcblry-v2',
    storageBucket: 'vcblry-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_JDCpc9DfwmhO6RyQ9D2k0skPd3dNeo',
    appId: '1:117150854963:ios:8978bdc9e792e7491a9846',
    messagingSenderId: '117150854963',
    projectId: 'vcblry-v2',
    storageBucket: 'vcblry-v2.appspot.com',
    iosBundleId: 'com.mateumiralles.vcblry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs_JDCpc9DfwmhO6RyQ9D2k0skPd3dNeo',
    appId: '1:117150854963:ios:8978bdc9e792e7491a9846',
    messagingSenderId: '117150854963',
    projectId: 'vcblry-v2',
    storageBucket: 'vcblry-v2.appspot.com',
    iosBundleId: 'com.mateumiralles.vcblry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6VvaQQ9Ky8cyryLoQ_SoSghwsTWEbLUo',
    appId: '1:117150854963:web:6e275a0de37bbe261a9846',
    messagingSenderId: '117150854963',
    projectId: 'vcblry-v2',
    authDomain: 'vcblry-v2.firebaseapp.com',
    storageBucket: 'vcblry-v2.appspot.com',
  );
}
